### ISSUE TITLE
Start `Obsession` on VimEnter

### ISSUE THREAD

**Issue by bruno-** [tpope/vim-obsession#17]
Hi, thanks for making this plugin.

I'd like to "track" sessions for \*all* the projects I'm working on, without bothering to invoke `:Obsession` when starting vim.
I have an autocommand for this:
```vim
au VimEnter *
  \ if !exists('g:this_obsession') && expand('%:p') !~# '\.git[\/].*MSG$' |
  \   silent Obsession |
  \ endif
```
The autocommand tries to avoid firing `Obsession` when:
- session is sourced with `vim -S`
- vim is opened to write commit messages

But, as I found out yesterday, this is not robust enough as apparently my session got overwritten when `git/rebase-merge/git-rebase-todo` was opened.

So questions:
- is there a robust autocommand that properly handles invoking `:Obsession` for the users?
- if such holly autocommand exists, does it make sense to put it in `vim-obsession`? Not "active" by default, but "option activated".

**Comment by tpope** [comment]
The second you start adding a blacklist of files not to fire on you have already lost. Where will this list live? Does every user have to maintain one individually? Will obsession.vim gain a monstrous one that is constantly churning as people send pull requests? This is lose-lose.

I'm also confused why maintaining a session is simultaneously important enough to mandate yet ephemeral enough to blindly clobber. Forget this commit message special casing; what happens when you go to resume working on a file and then you realize you destroyed all your context around it by opening it directly? Sounds like you are trying to have your cake and eat it too.

**Comment by tpope** [comment]
Oh, and I was rummaging around this repo after adding a status line flag for [flagship.vim](/tpope/vim-flagship), which I guess, in a very indirect way, might help your cause? Much easier to remember when there's a visual indicator as to whether obsession.vim is active, at least in my experience.

**Comment by bruno-** [comment]
Hey,
this question/request was opened quite a while ago. Since then I have first handed experienced the frustration of managing a blacklist of files. I forgot I even opened this issue though.

**Comment by tnguyen14** [comment]
Is there a standard way to start `Obsession` on `VimEnter`?

**Comment by tpope** [comment]
This is what I have used in the past, which restores a previous session but won't start a new one. For that part, you'd need to pull the `filereadable()` portion into a nested conditional.
```
if has('autocmd')
  autocmd VimEnter * nested
        \ if !argc() && empty(v:this_session) && filereadable('Session.vim') && !&modified |
        \   source Session.vim |
        \ endif
endif
```

**Comment by tnguyen14** [comment]
@tpope thanks! that's helpful. What is the check for `!&modified` for? Would it need to be pulled into the nested conditional as well?

**Comment by tpope** [comment]
Uh I believe that was to catch the `echo foo|vim -` case. Which means you would not want to pull it into the nested conditional.

**Comment by tnguyen14** [comment]
gotcha! thanks. So what I now have looks like this
```vim
	autocmd VimEnter * nested
		\ if !argc() && empty(v:this_session) && !modified|
		\   if filereadable('Session.vim') |
		\     source Session.vim |
		\   elseif |
		\     Obsession |
		\   endif |
		\ endif
```

Does that seem reasonable to you?

**Comment by tpope** [comment]
Yes.

**Comment by mb720** [comment]
This works nicely when opening a file (in a split or in a tab) from a Vim instance that already has Obsession running.

    autocmd VimEnter * nested
        \ if !argc() && empty(v:this_session) && !modified|
        \   if filereadable('Session.vim') |
        \     source Session.vim |
        \   elseif |
        \     Obsession |
        \   endif |
        \ endif

Yet when I open a file using `vim myFile` Obsession doesn't start, whether there's an existing Session.vim in the same directory or not.
`argc()` returned 1 (`true`) consistently and since that's negated `Session.vim` was never sourced. I suspect that's because Vim gets the filename to open as its first argument.

This is what I came up with instead which worked nicely for me:

    augroup ObsessionGroup
      autocmd!
      " When opening a file, start recording the Vim session with its tabs and splits. If Vim is called without arguments and there is already a session file, source it and record the session. Checking 'modified' avoids recording a session when reading from stdin. From https://github.com/tpope/vim-obsession/issues/17
      " !argc() makes sure we only source a session file if Vim was started without arguments. Otherwise we would open an old session instead of opening a file when calling 'vim my_file'.
      " Calling Obsession when the session is being recorded would pause the recording, that's why we check if v:this_session is empty.
      autocmd VimEnter * nested
          \ if !&modified |
          \   if !argc() && filereadable('Session.vim') |
          \   source Session.vim |
          \   echo "Existing session sourced, recording session" |
          \   elseif empty(v:this_session) |
          \     Obsession |
          \     echo "Started new session" |
          \   endif |
          \ endif
    augroup END

Then I realized I don't want to source an existing `Session.vim` when I call `vim` without arguments.

All I currently want is to start recording a session when it's not being done already:

    augroup ObsessionGroup
      autocmd!
      " When opening a file, make sure we record the Vim session with its tabs and splits. Checking 'modified' avoids recording a session when reading from stdin. From https://github.com/tpope/vim-obsession/issues/17
      " Calling Obsession when the session is being recorded would pause the recording, that's why we check if v:this_session is empty.
      autocmd VimEnter * nested
          \ if !&modified && empty(v:this_session) |
          \   Obsession |
          \   echo "Recording new session" |
          \ endif
    augroup END

I'm using Vim 8 and the current version of vim-obsession.
